Repository maplibre/swiftui-dsl, pull requests merged in 2024-10, with the labels that each got.

#54 Improving Camera Conversion
  Sources/MapLibreSwiftUI/MapViewCoordinator.swift
Labels: norelease

#53 Fix: recenter doesn't immediately take effect
  .swiftformat
  CHANGELOG.md
  Sources/MapLibreSwiftUI/Extensions/MapLibre/MLNMapViewCameraUpdating.swift
  Sources/MapLibreSwiftUI/MapViewCoordinator.swift
Labels: release:minor

#56 Upgrades
  CHANGELOG.md
  Package.resolved
  Package.swift
  Sources/MapLibreSwiftUI/Examples/Layers.swift
Labels: release:minor

#57 Fix the location manager being nil after Swiftui view update.
  CHANGELOG.md
  Sources/MapLibreSwiftUI/MapView.swift
Labels: release:patch
